import fs from 'fs';
import path from 'path';
import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import copyPlugin from 'esbuild-copy-static-files';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const outDir = prod ? 'dist' : 'test-vault/.obsidian/plugins/productivity-tools';

const createFilePlugin = ({ dest }) => ({
  name: 'create-file',
  setup(build) {
    build.onEnd(async () => {
      await fs.promises.mkdir(path.dirname(dest), { recursive: true });
      await fs.promises.writeFile(dest, '');
    });
  },
});

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: `${outDir}/main.js`,
  minify: prod,
  plugins: [
    copyPlugin({
      src: './manifest.json',
      dest: `${outDir}/manifest.json`,
    }),
    copyPlugin({
      src: './styles.css',
      dest: `${outDir}/styles.css`,
    }),
    ...(!prod ? [createFilePlugin({ dest: path.join(outDir, '.hotreload') })] : []),
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
